#include "PageWeb.h"

char *getPageWeb() {
 char *S="<!doctype html>\r"
  "<html><head><meta name='viewport' content='width=1050, initial-scale=1.0'><style>"
    "body {background: linear-gradient(#003,#226,#003);font-size:150%;text-align:center;}\r"
    ".ri { text-align: right;}"
    ".ce { text-align: center;}"
    ".grey { background-color:#ddd;}"
    ".blue { background-color:#ddf;}"
    ".foot { color:white;font-size:16px;}"
    "#DataLinky { background-color:white;display:inline-block;margin:auto;padding:4px;text-align:left;}\r"
    ".tableau { background-color:white;display:inline-block;margin:auto;padding:4px;}\r"
    "table {border:10px inset azure;}\r"
    "td { text-align: left;padding:4px;}\r"
    "svg { border:10px inset azure;background: linear-gradient(#333,#666,#333);}"
    "#LED{position:absolute;top:4px;left:4px;width:0px;height:0px;border:5px solid red;border-radius:5px;"
  "</style></head>"
  "<body  onload='LoadData();LoadHisto();' >\r"
    "<div id='LED'></div>\r"
    "<h2 style='text-align:center;color:white'>LINKY</h2>\r"
    "<div><div class='tableau'><table >\r"
      "<tr class='grey'><td>Puissance Apparente :</td><td id='Papp' class='ri'></td><td>VA</td></tr>\r"
      "<tr class='blue'><td>Courant Efficace :</td><td id='Iinst' class='ri'></td><td>A</td></tr>\r"
      "<tr class='grey'><td>Conso. <small>(heure pleine ou base)</small> :</td><td id='HCHP' class='ri'></td><td>Wh</td></tr>\r"
      "<tr class='blue'><td>Conso. <small>(heure creuse)</small> :</td><td id='HCHC' class='ri'></td><td>Wh</td></tr>\r"
    "</table></div></div>\r"
    "<p id='SVGp'></p>\r"
    "<p id='SVGi'></p>\r"
    "<p id='SVGhp'></p>\r"
    "<p id='SVGhc'></p>\r"
    "<br><br><div class='foot' >Donn&eacute;es brutes Linky en mode historique</div>\r"
    "<div><div id='DataLinky' ></div></div>\r"
    
    "<script src='JavascriptPageWeb'></script>\r"
    
    "<br></body></html>\r";
  return S;
 
}

//Les Wh cumulés données par le LINKY toutes les 5mn sont convertis en W (*12)
char *getJavascriptPageWeb(){
  char *S="var IdxMessageLinky=0;\r"
       "var MessageRecu='';\r"
       "function LoadData() {\r"
        "document.getElementById('LED').style='display:block;';\r"
        "var xhttp = new XMLHttpRequest();\r"
        "xhttp.onreadystatechange = function() { \r"
          "if (this.readyState == 4 && this.status == 200) {\r"
             "var DuLinky=this.responseText;\r"
             "var message=DuLinky.split('|');\r"
             "MessageRecu +=message[0];\r"
             "var groupes=MessageRecu.split('-----');\r"
             "var lg=groupes.length;\r"
             "if (lg>2){\r"
	              "MessageRecu='-----'+groupes[lg-1];\r"
                "document.getElementById('DataLinky').innerHTML = '<pre>'+groupes[lg-2]+'</pre>';\r"
                "var lignes=groupes[lg-2].split(String.fromCharCode(13));\r"
                "for (var i=0;i<lignes.length;i++){\r"
                  "var colonnes=lignes[i].split(' ');\r"
                  "if (colonnes[0]=='IINST'){\r"
                      "document.getElementById('Iinst').innerHTML = parseInt(colonnes[1]);\r"
                  "}\r"
                  "if (colonnes[0]=='PAPP'){\r"
                      "document.getElementById('Papp').innerHTML = parseInt(colonnes[1]);\r"
                  "}\r"
                  "if (colonnes[0]=='HCHP' || colonnes[0]=='BASE'){\r"
                      "document.getElementById('HCHP').innerHTML = parseInt(colonnes[1]);\r"
                  "}\r"
                  "if (colonnes[0]=='HCHC'){\r"
                      "document.getElementById('HCHC').innerHTML = parseInt(colonnes[1]);\r"
                  "}\r"
                "};\r"
                "document.getElementById('LED').style='display:none;';\r"
             "}\r"
             "IdxMessageLinky=message[1];\r"
             "setTimeout('LoadData();',1500);\r"
          "}\r"
          
        "};\r"
        "xhttp.open('GET', 'ajax_dataLinky?idx='+IdxMessageLinky, true);\r"
        "xhttp.send();\r"
      "}\r"
      "function LoadHisto() {\r"
        "var xhttp = new XMLHttpRequest();\r"
        "xhttp.onreadystatechange = function() { \r"
          "if (this.readyState == 4 && this.status == 200) {\r"
            "var retour=this.responseText;\r"
            "var champs=retour.split('|');\r"
            "var tabI=champs[0].split(',');\r"
            "var tabP=champs[1].split(',');\r"
            "var tabHC=champs[2].split(',');\r"
            "var tabHP=champs[3].split(',');\r"
            
            "Plot('SVGhc',tabHC,'yellow','Puissance Heure Creuse W');\r"
            "Plot('SVGhp',tabHP,'aqua','Puissance Heure Pleine ou Base W');\r"
            "Plot('SVGi',tabI,'lightgreen','Intensit&eacute; A');\r"
            "Plot('SVGp',tabP,'red','Puissance VA');\r"
            
            "setTimeout('LoadHisto();',300000);\r"
          "}\r"
          
        "};\r"
        "xhttp.open('GET', 'ajax_histo', true);\r"
        "xhttp.send();\r"
      "}\r"
      "function Plot(SVG,Tab,couleur,titre){\r"
          "var Vmax=0;\r"
          "for (var i = 0; i < 600; i++) {\r"
                "Vmax = Math.max(Tab[i], Vmax);\r"      
          "}\r"    
          "var cadrage=1;\r"
          "var cadrage1=1000000;"
          "var cadrage2=[10,8,5,4,2,1];\r"
          "for (var m=0;m<7;m++){\r"
            "for (var i=0;i<cadrage2.length;i++){\r"
               "var X=cadrage1*cadrage2[i];\r"
               "if ((Vmax)<=X) cadrage=X;\r"
            "}\r"
            "cadrage1=cadrage1/10;\r"
          "}\r"
          "var S= \"<svg height='250' width='1030' >\";\r"
          "S += \"<line x1='100' y1='20' x2='100' y2='220' style='stroke:white;stroke-width:2' />\";\r"
          "S += \"<line x1='100' y1='220' x2='1000' y2='220' style='stroke:white;stroke-width:2' />\";\r"
          "const d = new Date();\r"
          "var H0=d.getHours()+d.getMinutes()/60;\r"
          "var H00= 4*Math.floor(H0/4);\r"
          "var X0=18*(H00-H0);\r"
          "for (var h=0;h<=50;h=h+4){\r"
            "var X=1000+X0-h*18;\r"
            "var H=(H00-h+72)%24;\r"
            "S +=\"<line x1='\"+X+\"' y1='220' x2='\"+X+\"' y2='226' style='stroke:white;stroke-width:2' />\";\r"
            "X=X-8;\r"
            "S +=\"<text x='\"+X+\"' y='242' style='font-size:16px;fill:white;'>\"+H+\"</text>\";\r"
          "}\r"
          "S +=\"<text x='980' y='217' style='font-size:14px;fill:white;'>heure</text>\";\r"
          "for (var y=0 ;y<=10;y=y+2){\r"
           
            "var Y=220-20*y;"
            "S +=\"<line x1='100' y1='\"+Y+\"' x2='1000' y2='\"+Y+\"' style='stroke:white;stroke-width:1;stroke-dasharray:2 10' />\";\r"
            "Y=Y+7;\r"
            "var T=cadrage*y/10;T=T.toString();"
            "var X=90-9*T.length;"
            "S +=\"<text x='\"+X+\"' y='\"+Y+\"' style='font-size:16px;fill:white;'>\"+T+\"</text>\";\r"
          "}\r"
          "S +=\"<text x='450' y='18' style='font-size:18px;fill:white;'>\"+titre+\"</text>\";\r"
          "S += \"<polyline points='\";\r"
            "for (var i = 0; i < 600; i++) {\r"
              "var Y = 220 - 200 * Tab[i] / cadrage;\r"
              "var X = 100+1.5 * i;\r"
              "S += X + ',' + Y + ' ';\r"
            "}\r"
            "S += \"' style='fill:none;stroke:\"+couleur+\";stroke-width:4' />\";\r"
            "S += \"</svg>\";\r"
            "document.getElementById(SVG).innerHTML = S;\r"
      "}\r";
  return S;
}
